### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by ngouy** [kigiri/learn#6]
So as i sayed i'm not (yet ^^) pro in js crafting but i have some basics cuz i'm at the end of a 6 months practice where I never stop to learn with emberjs (so good framework btw ^^);

So if u need little help some where, let's do it, doing my best and open to learn / correction / advices ofc
- [x] build and launch on local
- [ ]
  ...

Ps: j'ai tenté d'écrire en anglais pk mon chef me dit tj osef dev avec des français ou pas on ouvre ses issues, on comment, on commit en anglais... et comme tu dis qu'il faut apprendre l'anglais pk il Faut ! Ben voila

**Comment by rubenamran** [comment]
Lol au début je m'étais dit woow la classe un américain et tout qui se joint au projet c'est la classe et apres t'as commencé à parler en francais en mode kikoo j'ai déplanné :p

**Comment by ngouy** [comment]
Mdr ^^
Ricain de rien du tout, je suis un bon français de la campagne qui s'est retrouvé à 42 en partie a cause de toi et tes premières vidéos que je mataient pdt mes heures de déprimes en prépa x)

Sinon j'ai essayer de lancer le projet en local, il a fallu que j'ajoute un flagu (mais j'ai peut etre pas utilisé le bon) pour la compatibilité ECMAScript 6 et pui j'ai du installer en plus uglify.js pk il était pas dans le package.json mais il était require.

Mais meme apres ca j'ai plein de lignes rouge qui s'affichent quand je tape 
$> node dev-server.js

C'est normal ou ? ... je connais pas encore très bien nodejs

**Comment by kigiri** [comment]
C'est cool de parler english :+1: 

Pour ce qui est de lancer le projet, j'ai test sur OSX, CentOS et Windows Node >= 5.3.

Normalement tu a juste a faire un npm install puis un npm start et voila ca run en dev.

Merci de me faire suivre si ya 
_edit :_
En fait c'est le chaos dans les dependences du package.json la je regle ca :)

**Comment by ngouy** [comment]
Roger that, wasn't launching the wright cmd

**Comment by kigiri** [comment]
Ok fixed the missing dependencies, is it working now ?

**Comment by ngouy** [comment]
Pulling it and back in few secs

_edit:_

Isnt working. Same issues as previously :

ERROR in ./src/dev-main.js
Module not found: Error: Cannot resolve module 'global/window'

Doing this on all module 'global/*' cuz :
- looking for modules in .../app/src but .../app/src/global doesn't exists
- looking for modules in .../node_modules but .../node_modules.global doesn't exists

**Comment by kigiri** [comment]
you are starting with `npm start` right ?
Try delete node_modules and re-install, i did a clean install on my mac and my PC and they both worked

maybe install globaly `webpack` and `webpack-dev-server` with `npm install -g webpack and webpack-dev-server` ?

**Comment by ngouy** [comment]
Trying it as u sayed

**Comment by kigiri** [comment]
I use `global` which is installed by `dom-delegator` for me and that seem to be what you are missing for some reason.
I will add it in the dependencies

**Comment by ngouy** [comment]
after pull ur last commit, and install with `-g` flag, it's better. But only thanks to `dom-delegator`
I'm still missing some things, to know : `cuid`, `raf` and `performance-now` modules

They are common modules and i think it's because u got them locally installed
I will try to install them through `npm intall` and i will try it again.

_edit_
After : 
`$> npm install cuid`
`$> npm install raf`
`$> npm install performance-now` 
It works like a charm

**Comment by ngouy** [comment]
I'm now enjoing your video ;) :+1: Let's create my first js function

```
(() => {
  console.log('let's go baby');
}).call()
```

#joking
